### PR TITLE
Added the simulation movie for the Python script

### PR DESCRIPTION
**Pull request by TommasoVandermeer**
I downgraded the Numpy version of my Python env to 1.21.1 to avoid errors while running the code. In addition, I added a script to the Python version to generate a video of the simulation. This was done through the use of _**matplotlib animation**_ classes, and the _**screeninfo**_ package to get the screen size of the monitor used (`pip install screeninfo`).

In order to use the FFMpegWriter you need to install the FFmpeg on your system, use the following command: `sudo apt install ffmpeg`.

### CODE REVIEW

**Review by francescofarina — CHANGES_REQUESTED** [review]
Great! Before approving, can you please remove the auxiliary files and the mp4?

**Comment by TommasoVandermeer** [comment]
I removed mp4 and auxiliary files. Thank you!

**Review by francescofarina — APPROVED** [review]

**Comment by francescofarina** [comment]
Feel free to merge

**Comment by TommasoVandermeer** [comment]
Shouldn't you merge? Sorry, it is my first pull request. I noticed that "only those with write access to this repository can merge pull requests".

**Comment by francescofarina** [comment]
> Shouldn't you merge? Sorry, it is my first pull request. I noticed that "only those with write access to this repository can merge pull requests".

You should have write access but I'll merge it.

**Pull request merged**
